### ISSUE TITLE
[Feature Request] Variable initial distance from the undulator

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#10]
The head of the bunch is placed at 2*lu distance from the beginning of the undulator.
This could be modifiable by the user

**Comment by aryafallahi** [comment]
I agree with this change. It probably does not need testing since it is just a small change. Please go ahead with your implementation and I will comment on it subsequently.

**Comment by aryafallahi** [comment]
the manual needs to be updated. currently only refcard is updated.
