### ISSUE TITLE
[Small Code Change] Change name of squared of norm

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#11]
The FieldVector class has a method
``` 
    ElementType norm()
    {
      return ( a[0]*a[0] + a[1]*a[1] + a[2]*a[2] );
    };
```

Intuitively, for me at least, the norm would have a square-root. This looks like the squared of the norm.
I propose that this method's name is changed to norm2()

**Comment by aryafallahi** [comment]
This is a good change. I also suggest we change this norm() to norm2() and then change all the related functions in the code.

Then we do a compilation to make sure that it is correct. It does need any testing.

Then, we add a function norm(), with square root that we can use later in the next implementations.

**Comment by aryafallahi** [comment]
issue closed

**Comment by aryafallahi** [comment]
code is updated and tested
