### ISSUE TITLE
Magnetic field in undulator

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#16]
I have been scratching my head the past few days because I couldn't understand how the particles were behaving along the x-axis. 

It seemed as if all particles with x > 0 were being focussed, and particles with x < 0 were being defocussed, but only while the particles were inside the undulator.

Now I found the source of the [problem](https://github.com/aryafallahi/mithra/blob/master/src/solver.cpp#L1395):

```
ubp.bt[2] += ub_.b0 * sqrt( ( ubp.cy * ubp.cy - 1.0 ) * ( 1.0 - ubp.sz * ubp.sz ) );
```

This can only give positive values!!

![B_comparison](https://user-images.githubusercontent.com/45881038/75333537-93fe4d00-5886-11ea-8412-ae7e0d58da21.png)

I had always seen a strange behaviour in my simulations, but I wasn't sure if it was normal or not. 
Eventually I decided to investigate it and found out.

I think in your simulations it is not noticeable because K is small, hence B_z is very small. If the transverse size is small and B_z is small, then this effect is barely noticeable.
However, with a large K and a large transverse size, the effect is not negligible.
In the images below you can see a clear asymmetry along the x-axis due to this problem:

Transverse electron density at two screens, before and after the undulator:
![example1](https://user-images.githubusercontent.com/45881038/75334225-be043f00-5887-11ea-8cc0-449789b25aae.png)

Electron density along t and x axis, at two screens, before and after the undulator:
![example2](https://user-images.githubusercontent.com/45881038/75334226-be9cd580-5887-11ea-81c7-1e53b8fb65d3.png)

**Comment by arnaualba** [comment]
I will correct it with 
```
ubp.bt[2] += ub_.b0 * sinh(ub_.ku * ubp.ly) * cos(ub_.ku * ubp.lz);
```

And if the results are OK I will make a pull request for this issue

**Comment by aryafallahi** [comment]
All I can say is that you are correct. This is a bug that I never noticed. Thanks in advance for correcting it.
