### ISSUE TITLE
[Feature Request] Add a way to call MITHRA from another program

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#21]
In order to call MITHRA from OPAL in a cleaner way, I would like to add an option in `initializeBunch()` which doesn't add any particles to `chargeVectorn_`, because OPAL (or another program) will have already filled in `chargeVectorn_`.

For this I would move `chargeVectorn_.clear()` to the `Solver` constructor.
Then in `initializeBunch()`I would add a `if bunchType == "other" -> don't add anything to the chargeVectorn_`,

**Comment by aryafallahi** [comment]
For the moment, in the master code, we do not have bunchType == "other" option. So feel free to add it. I think it does not change anything in the code.
