### ISSUE TITLE
[Feature Request] End simulation at point

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#26]
It would be useful that one could choose a z-coordinate, and when all the particles have passed this point the simulation stops. 

We could have a coordinate `Double mesh_.zEnd_` and a flag ` bool mesh_.run_`.

In fdtd.cpp we could do 
```
while ( ( time_ < mesh_.totalTime_ ) && ( mesh_.run_ ) )
```
Where `mesh_.run_` is checked at each loop:
```
for ( iterQ ... )
{
   lz = gamma_ * ( iterQ->rnp[2] + beta_ * c0_ * ( timeBunch_ + dt_ ) );
   mesh_.run_ = lz < mesh_.zEnd_;
   if ( mesh_.run_)
       continue;
}
```

**Comment by aryafallahi** [comment]
I think this feature is useful. But, I would not add a new loop over millions of particles in each iteration just to check for this feature.

Instead, I think it is better to calculate the total time needed for the last particle to arrive at this point and then change the totaltime variable accordingly. Indeed, this is what I assume a user can do. It is simply setting the total time slightly larger than zend/c. But, we can also add it as a feature.

**Comment by arnaualba** [comment]
I agree, what you suggest is  much more sensible approach.
I will try to add it when I have time with a merge request
