### ISSUE TITLE
[Bug] Bunch update time step

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#27]
The bunch time step is given by the user, and then MITHRA adapts it such that the field update time step is an integer multiple of the bunch time step:
```
bunch_.timeStep_ = mesh_.timeStep_ / ceil(mesh_.timeStep_ / bunch_.timeStep_);
nUpdateBunch_    = mesh_.timeStep_ / bunch_.timeStep_;
```

If the user doesn't give   `bunch-time-step` it defaults to 0, which is bad because then the simulation hangs.

I think  the bunch-update time step should default to being the same as the field time step. 
```
if (bunch_.timeStep_ == 0) bunch_timeStep = mesh_.timeStep_ ;
```

Do you agree?

**Comment by aryafallahi** [comment]
Yes, I agree. Good point. Would you add your line and put a merge request?
