### ISSUE TITLE
[Enhancement] Calculation of total time from total distance

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#50]
The current calculation of `mesh_.totalTime_` from a `mesh_.totalDist_`  given by the user, overestimates the necessary time, and the tail of the bunch ends much further downstream than the actual given `totalDist_`:

```	
	mesh_.totalTime_ = ( mesh_.totalDist_ / gamma_ - zminG ) / ( beta_ * c0_ ) - dt_;
 ```

For the implementation in OPAL it really is necessary that the bunch's tail ends at `totalDist_` in the lab frame, or very close to it.
I propose a different way to calculate the total time. It is more accurate. I have attached a small note describing the derivation

[computeTime.pdf](https://github.com/aryafallahi/mithra/files/4826695/computeTime.pdf)

**Comment by arnaualba** [comment]
Note that for this calculation I assume that totalDist_ is longer than the undulator (or array of undulators). So the end point is somewhere after the last undulator

**Comment by aryafallahi** [comment]
Hi Arna,
thanks for the correction. I think your implementation is better. I will just merge your pull request.
