### ISSUE TITLE
[Feature Request] Function for hello message

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#54]
The hello message with the copyright and author information is printed from within the `mithra.cpp` file. 
If you agree, I would like to make this into a function `helloMessage()` that is called from `mithra.cpp`.

This would be really useful as in OPAL when we use the Mithra functions we also print out this hello message. At the moment I copy pasted the hello message from `mithra.cpp`, but if the copyright or authors change this will become outdated in OPAL. If I could call a `MITHRA::helloMessage()` function it would be much better.

Let me know if that would be OK. Thanks

**Comment by aryafallahi** [comment]
yes, it is fine with me. no problem.
