### ISSUE TITLE
reduce the group velocity of laser

### ISSUE THREAD

**Issue by HLQzZ** [aryafallahi/mithra#67]
Dear developers,

I want to reduce the group velocity of the optical undulator (gaussian beam) to make it interact with the electron beam.Is there any way to reduce the group velocity of the optical undulator?
Any help or suggestion will be helpfuI 

Thanks.

HLQ

**Comment by aryafallahi** [comment]
Hi HLQ,

Sorry for the late reply. We do not use this channel here for these questions and is mainly used for discussing new pull requests. In the future please write to my email address mentioned in the manual.

Currently, we do not have such a feature. The Gaussian beam is considered to propagate in free space and there are limitations on the phase and group velocities derived from beam spot size. So, once you set the spot size these values are correspondingly set. 

Best regards,

Arya
