### ISSUE TITLE
[Bug] Particle emission

### ISSUE THREAD

**Issue by arnaualba** [aryafallahi/mithra#9]
As of now, in the Lorentz boost the particles are pushed back in time such that they are all at time = 0 in the bunch-rest-frame. 

However, they are pushed back in a straight line, but when the simulation is running, if space charge is strong, the particles will not have a straight trajectory.
Because of this, when particles reach the undulator they will not have the correct position or energy.

This can be solved by having the particles move in a straight line (by having them not feel any EM fields) until some "point of emission" or until they have reached their intended original position.

**Comment by aryafallahi** [comment]
This change is also good and should be done. But, we need testing it first. So, it may be a little time taking. I would start doing it once the other three issues are closed.

**Comment by aryafallahi** [comment]
and I think the general approach you wrote is good. We need to implement it correctly.

**Comment by aryafallahi** [comment]
@arnaualba: I have implemented this feature but it is not tested. I will test the code on my side. I ask that you also test the code on your side, before closing the issue.

**Comment by arnau** [comment]
@aryafallahi you were probably aiming for @arnaualba :)

**Comment by arnaualba** [comment]
Thank you @aryafallahi, the solution you implemented looks cool, and I agree with it.

I will also test it.

**Comment by arnaualba** [comment]
Hi @aryafallahi 
I have tried out a bit the emission model with some of your examples but I had actually not noticed this bug that you just corrected, so I didn't test it thoroughly enough.
I will do some more tests.

**Comment by aryafallahi** [comment]
@arnaualba: I tested the previous implementation with a FEL-IR simulation without space-charge. Intuitively, it should have given the same result. But, it was not producing similar result. After this correction, it was fine. I am doing more tests and will soon close this issue and go to the next one.
